### PR TITLE
Doxygen Documentation: limits.h Fixes #21

### LINKED ISSUE #21: Doxygen Documentation: Limits.h
Limits.h needs documentation

### PR DESCRIPTION
**Pull request by seekaddo**
Doc for limits done!!.

### CODE REVIEW

**Comment by phillipjohnston** [comment]
One typo to fix, otherwise it looks good! Thanks @seekaddo

**Comment by seekaddo** [comment]
@phillipjohnston Done!!. I hope you mean the first three constants

**Comment by phillipjohnston** [comment]
Still looks like the typos are there. Exapnds needs to be corrected to "Expands" in multiple places

**Comment by seekaddo** [comment]
@phillipjohnston  hahaha, Thanks, You are right. I found a different typo. Thanks.

**Comment by seekaddo** [comment]
I think it looks good now.

**Comment by phillipjohnston** [comment]
It does, thanks again!

**Pull request merged**
